In [26]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

### 0.Intro
- Series가 인덱스를 가지는 1차원 배열
- DataFrame은 행 인덱스와 열 인덱스를 가지는 2차원 배열

**2차원 배열응ㄹ 정렬된 1차원 열의 연속으로 볼수 잇듯이 Dataframe은 정렬된 Series 객체의 연속으로 볼수 있다**

In [33]:
import pandas as pd
import numpy as np

### 1.Dataframe 
<par> 다양한 방식으로 선언 할 수 있다. 이에 대해서는 3.Creation에서 살펴보겠다


- colums(열 인덱스) index(행 인덱스)를 지정해줄수도 있다
- 지정해주지 않으면 자동으로 0-based 인덱스가 생성된다

In [7]:
# 간단한 예시
# 2차원 데이터

pd.DataFrame([[1,2,3,4],[5,6,7,8]]) # => 행 index와 row index가 동시에 존재하는것을 확인할수 있다

0  1  2  3
0  1  2  3  4
1  5  6  7  8

In [8]:
# column index 둘다 명시
pd.DataFrame([[1,2,3,4],[5,6,7,8]],columns = ['서울','부산','경기','대전'],index=['오전','오후'])

서울  부산  경기  대전
오전   1   2   3   4
오후   5   6   7   8

In [29]:
# 당연히 속성 접근 가능하지
df01 = pd.DataFrame([[1,2,3,4],[5,6,7,8]],columns = ['서울','부산','경기','대전'],index=['오전','오후'])
df01.index
df01.columns

Index(['오전', '오후'], dtype='object')

Index(['서울', '부산', '경기', '대전'], dtype='object')

- dtype도 지정해줄수 있다
    - pd.DataFrame()에서 각 열마다 dtype 지정해줄수 있을거 같지만 안된다 => single type만 가능하다
    - 개별적으로는 각 열마다 dtype 가능하다

In [9]:
# 생성할때는 single 
pd.DataFrame([[1,2],[5,6]],columns=['a','b'],dtype=(float))

a    b
0  1.0  2.0
1  5.0  6.0

In [10]:
# 개별적으로 update 가능하다 
df01 = pd.DataFrame([[1,2],[5,6]],columns=['a','b'])
df01['a'] = df01['a'].astype(float)
df01

a  b
0  1.0  2
1  5.0  6

### 2.DataFrame creation
**DataFrame 차원에서 key값은 column단위다, Numpy에서는 키값이 index로 row단위였다**
- 더 자세하게 세부적으로 나눌수 있지만 간략하게는 다음과 같다
    - 1차원 => column으로 들어간다
        - 1차원 ndarray 혹은 1차원 ndarray를 구성하는 data(list,tuple,range)
        - 단일 Series 혹은 Series를 구성하는 data (list,tuple,range,ndarray)
    - 2차원 => row 단위로 들어간다
        - [{'key1':value1, 'key2':value2,,,},{'key1':value1, 'key2':value2,,,}]
        - 2차원 데이터 혹은 ndarray를 구성하는 데이터
    - dict => key값에 해당하는 데이터가 하나의 column으로 들어간다
        - {'key1':Series,'key2':Series,,}
        - {'key1':data,'key2':data,,} Series를 구성하는 data(list,tuple,range)

> 1차원 예시들 -> column 단위로 들어간다

In [12]:
# 1차원 ndarray
display(pd.DataFrame([1,2,3]))
display(pd.DataFrame((1,2,3)))

0
0  1
1  2
2  3

0
0  1
1  2
2  3

In [6]:
# (1차원) series 이용해서 data frame 만들어보자
# Series(1차원) 객체가 열단위로 들엉갔다
# 또한 Seiries 이름이 column명으로 들어간걸 확인할수 있다

series01 = pd.Series([100,200,50,200,30],index=['JPN','KOR','UK','NL','GER'],name='pop')
df01 = pd.DataFrame(series01)
df01


pop
JPN  100
KOR  200
UK    50
NL   200
GER   30

> 2차원 예시들 -> row 단위로 들어간다

In [13]:
# 2차원 ndarray
display(pd.DataFrame([[1,2,3],[4,5,6]]))
display(pd.DataFrame([(1,2,3),(4,5,6)]))
display(pd.DataFrame(((1,2,3),(4,5,6))))

0  1  2
0  1  2  3
1  4  5  6

0  1  2
0  1  2  3
1  4  5  6

0  1  2
0  1  2  3
1  4  5  6

In [14]:
# 2차원 with pd.Series 객체
series01 = pd.Series([100,200,50,200,30],index=['JPN','KOR','UK','NL','GER'],name='pop')
series02 = pd.Series([20,300,10,20,3000],index=['JPN','KOR','UK','NL','GER'],name='area')
pd.DataFrame([series01,series02])

JPN  KOR  UK   NL   GER
pop   100  200  50  200    30
area   20  300  10   20  3000

> dictionary 형식 예재들 -> key: column key , 데이터는 컬럼 단위로

In [15]:
# 2차원 ; list of dict
# 여기서 key는 컬럼 단위다
pd.DataFrame([{'a':1,'b':2,'c':3},{'a':1,'b':2,'c':3}])

a  b  c
0  1  2  3
1  1  2  3

In [16]:
# 2차원 ; list of dict
# 일부 키 누락
# - list of dict에서 일부 키가 누락되더라도 알아서 NaN으로 생성된다
pd.DataFrame([{'a':1,'c':3},{'a':1,'b':2}])

a    c    b
0  1  3.0  NaN
1  1  NaN  2.0

In [17]:
# 딕셔너리 형식 
pd.DataFrame({'population':[100,200,300],'country':['KOR','JPN','CHN']})

population country
0         100     KOR
1         200     JPN
2         300     CHN

In [20]:
# 딕셔너리 형식 (가장 정형화된)
population = pd.Series([100,200,300,400])
country = pd.Series(['KOR','JPN','CHN','USA'])
pd.DataFrame({'population':population,'country':country})

population country
0         100     KOR
1         200     JPN
2         300     CHN
3         400     USA

In [21]:
# 위와 동일한 느낌이다
series01 = pd.Series([100,200,50,200,30],index=['JPN','KOR','UK','NL','GER'],name='pop')
series02 = pd.Series([20,300,10,20,3000],index=['JPN','KOR','UK','NL','GER'],name='area')

pd.DataFrame({series01.name:series01,series02.name:series02})

pop  area
JPN  100    20
KOR  200   300
UK    50    10
NL   200    20
GER   30  3000

### 3.DataFrame의 유용한 속성들 
- 하나 유이할건 values는 ndarray 형식으로 값들을 돌려준다
- 아래 함수에 정의했다

In [23]:
def dfinfo(df):
    display(df)
    print('shape:',df.shape)
    print('size:',df.size)
    print('ndim:',df.ndim)
    print('index:',df.index)     # row index
    print('columns:',df.columns) # column inex 
    print('values:\n',df.values,type(df.values)) #ndarray 형식으로 나온다

In [24]:
df01 = pd.DataFrame([[1,2,3,4],[5,6,7,8]],columns = ['서울','부산','경기','대전'],index=['오전','오후'])
dfinfo(df01)

서울  부산  경기  대전
오전   1   2   3   4
오후   5   6   7   8

shape: (2, 4)
size: 8
ndim: 2
index: Index(['오전', '오후'], dtype='object')
columns: Index(['서울', '부산', '경기', '대전'], dtype='object')
values:
 [[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


### 4.DataFrame 연산
- Series와 동일하다
    - Numpy universial function을 활요한 벡터 연산 지원한다
    - index를 기준으로 연산된다
    - index가 다를시 결과는 NaN
- 추가적으로 numpy 배열에서 보았던 것처럼 broadcasting도 가능하다
    - numpy broadcasting의 규칙을 따른다 
    - 웬만하면 ndarray 객체를 사용해서 연산하자 => 에러 발생 안한다
    - df 와  series 사이의 연산에는 index 보존 그대로 적용된다

In [36]:
# 벡터 연산
df01 = pd.DataFrame([[1,2,3],[4,5,6]])
display(df01+1)
display(df01*10)
display(df01/30)

0  1  2
0  2  3  4
1  5  6  7

0   1   2
0  10  20  30
1  40  50  60

0         1    2
0  0.033333  0.066667  0.1
1  0.133333  0.166667  0.2

In [37]:
# index를 보존한다
# index 가 맞지 않는 부분은 NaN으로 표시된다
df01 = pd.DataFrame([[1,2,3],[4,5,6]],columns=['A','B','C'])
df02 = pd.DataFrame([[1,2,3,4],[5,6,7,8]],columns=['A','B','C','D'])
df01
df02
df01+df02

A  B  C
0  1  2  3
1  4  5  6

A  B  C  D
0  1  2  3  4
1  5  6  7  8

A   B   C   D
0  2   4   6 NaN
1  9  11  13 NaN

In [38]:
# 반드시 인덱스가 있어야 계산할수 있다는 것은 아니다
df01 = pd.DataFrame([[1,2,3],[4,5,6]],columns=['A','B','C'])
df01
np.arange(1,7).reshape(2,3)
df01+ np.arange(1,7).reshape(2,3)

A  B  C
0  1  2  3
1  4  5  6

array([[1, 2, 3],
       [4, 5, 6]])

A   B   C
0  2   4   6
1  8  10  12

In [39]:
# broadcasting
# numpy의 broadcastng 규칙을 따른다
df01 = pd.DataFrame([[1,2,3],[4,5,6]],columns=['A','B','C'])
display(df01 + np.array([1000,2000,3000])) #(2,3) + (3,) => (2,3) + (1,3) => (2,3) + (2,3)
display(df01 + np.array([1000,2000]).reshape(2,1)) #(2,3) + (2,1) => (2,3) + (2,3)

A     B     C
0  1001  2002  3003
1  1004  2005  3006

A     B     C
0  1001  1002  1003
1  2004  2005  2006

#### **연산 심화**

In [44]:
# broadcasting 
# df + series
# index 영향을 받는다
df01 = pd.DataFrame([[1,2,3],[4,5,6]],columns=['A','B','C'],index = ['가','나'])

df01
df01.iloc[0] # 행

# 위에 두개 더할거다
# 아래처럼 broad casting 발생
#(2,3) + (3,) => (2,3) + (1,3) => (2,3) + (2,3)
# 근데 df01.iloc[0] 인덱스 있다 ['A','B','C']
# 문제 없이 잘 더해질거다

df01 + df01.iloc[0] 

A  B  C
가  1  2  3
나  4  5  6

A    1
B    2
C    3
Name: 가, dtype: int64

A  B  C
가  2  4  6
나  5  7  9

In [45]:
# 위와 동일한 논리다
df01 = pd.DataFrame([[1,2,3],[4,5,6]],columns=['A','B','C'],index = ['가','나'])
df01 + pd.Series([100,100,100],index=['A','B','C'])

A    B    C
가  101  102  103
나  104  105  106

> Series에도 봤지만 인덱스 다르면 계산이 안된다\
> 계산도 안되고 그때 index 둘다 들어간다

In [48]:
df01 = pd.DataFrame([[1,2,3],[4,5,6]],columns=['A','B','C'],index = ['가','나'])
df01 + pd.Series([100,100,100],index=['A','B','D'])

A      B   C   D
가  101.0  102.0 NaN NaN
나  104.0  105.0 NaN NaN